2024-05-09 11:58:44,555 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}, 6 dimensions and 150 particles
2024-05-09 19:48:22,366 - pyswarms.single.global_best - INFO - Optimization finished | best cost: 87.39366385136736, best pos: [0.0219549  0.07674094 0.03473413 0.25265492 0.47329935 0.63552867]
2024-06-07 12:09:27,986 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (9,)
Traceback (most recent call last):
  File "C:\Users\Matthew\Documents\University\4\700\Software\LQR-Control-with-RL\.conda\Lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
                   ^^^^^^^^^^^^^^^^^^
  File "numpy\\random\\mtrand.pyx", line 1171, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 600, in numpy.random._common.cont
  File "_common.pyx", line 517, in numpy.random._common.cont_broadcast_2
  File "__init__.cython-30.pxd", line 780, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (150, 9) and arg 1 with shape (150, 6).
2024-06-07 12:11:09,889 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (9,)
Traceback (most recent call last):
  File "c:\Users\Matthew\Documents\University\4\700\Software\LQR-Control-with-RL\.conda\Lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
                   ^^^^^^^^^^^^^^^^^^
  File "numpy\\random\\mtrand.pyx", line 1171, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 600, in numpy.random._common.cont
  File "_common.pyx", line 517, in numpy.random._common.cont_broadcast_2
  File "__init__.cython-30.pxd", line 780, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (150, 9) and arg 1 with shape (150, 6).
2024-06-07 12:11:44,726 - pyswarms.backend.generators - ERROR - Bounds and/or init_pos should be of size (9,)
Traceback (most recent call last):
  File "c:\Users\Matthew\Documents\University\4\700\Software\LQR-Control-with-RL\.conda\Lib\site-packages\pyswarms\backend\generators.py", line 81, in generate_swarm
    pos = center * np.random.uniform(
                   ^^^^^^^^^^^^^^^^^^
  File "numpy\\random\\mtrand.pyx", line 1171, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 600, in numpy.random._common.cont
  File "_common.pyx", line 517, in numpy.random._common.cont_broadcast_2
  File "__init__.cython-30.pxd", line 780, in numpy.PyArray_MultiIterNew3
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (150, 9) and arg 1 with shape (150, 6).
2024-06-07 12:12:15,158 - pyswarms.single.global_best - INFO - Optimize for 1000 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-06-07 12:13:31,772 - pyswarms.single.global_best - INFO - Optimize for 2500 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-06-07 12:20:24,304 - pyswarms.single.global_best - INFO - Optimize for 2500 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-06-07 12:22:42,393 - pyswarms.single.global_best - INFO - Optimize for 2500 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-06-07 12:23:58,529 - pyswarms.single.global_best - INFO - Optimize for 2500 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-06-07 12:27:20,742 - pyswarms.single.global_best - INFO - Optimize for 2500 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
2024-06-07 12:28:44,486 - pyswarms.single.global_best - INFO - Optimize for 2500 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}
